language: node_js
node_js:
  - "10"
  - "11"
  - "12"
sudo: false
dist: trusty
cache:
  directories:
    - node_modules
after_script:
  - |
    # Upload coverage to coveralls if exists
    if [[ -e ./coverage/lcov.info ]]; then
      npm install --save-dev coveralls@2
      coveralls < ./coverage/lcov.info
    fi
